version: '3.8'

services:
  mysql:
    image: mysql:8.0
    #platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: debit_manager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: 'oshanh/debitmanager-backend:64'
    #platform: linux/amd64
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/debit_manager?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - uploads_data:/uploads

  frontend:
    image: 'oshanh/debitmanager-frontend:64'
    #platform: linux/arm64
    # build: 
    #   context: ./frontend
    #   dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  uploads_data: