services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: RashmiTyre
      MYSQL_DATABASE: credit
      MYSQL_USER: credit_user
      MYSQL_PASSWORD: RashmiTyre
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./credit-manager-frontend
    image: credit-manager-frontend
    ports:
      - 3000:3000  # Expose frontend on localhost:5173

  backend:
    build: ./credit-manager-backend 
    image: credit-manager-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/credit?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: credit_user
      SPRING_DATASOURCE_PASSWORD: RashmiTyre
    depends_on:
      - mysql
    ports:
      - 8081:8081  # Expose backend on localhost:8081    

volumes:
  mysql_data:
      